# Generated by Django 4.2.2 on 2023-07-30 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_options_rename_post_comment_article_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['creacion']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='active',
            new_name='activo',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='updated',
            new_name='actualizacion',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='article',
            new_name='articulo',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='contenido',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created',
            new_name='creacion',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='usuario',
        ),
    ]
