# Generated by Django 4.2.2 on 2023-07-31 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comment_options_rename_active_comment_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='usuario',
            field=models.CharField(default='anonimo', max_length=100),
            preserve_default=False,
        ),
    ]
